'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.FileLinks

    Partial Public Class Settings

        '''<summary>
        '''tblGeneral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblGeneral As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plSelectFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSelectFolder As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSelectFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSelectFolder As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDisplayFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDisplayFolders As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDisplayFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDisplayFolders As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plDisplayFilesInFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDisplayFilesInFolders As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDisplayFilesInFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDisplayFilesInFolders As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTrackDownloads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTrackDownloads As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkTrackDownloads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTrackDownloads As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plExtensionFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExtensionFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtExtensionFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExtensionFilter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortBy As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plMaxFileSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxFileSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaxFileSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxFileSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxFileSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxFileSize As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valMaxFileSizeIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxFileSizeIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plSecureUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSecureUrl As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSecureUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecureUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshImageSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshImageSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblImageSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblImageSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plResizeImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plResizeImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkResizeImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkResizeImages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plRenameImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRenameImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkRenameImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRenameImages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCompressionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCompressionType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCompressionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCompressionType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valImageWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valImageHeightIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageHeightIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''dshTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplate As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplateHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItem As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplateItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubItem As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplateSubItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateSubItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubEmpty As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplateSubEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateSubEmpty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplateFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmpty As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplateEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateEmpty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshTemplateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplateHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplateHelp As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblContentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContentType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDateCreated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateCreated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDateModified control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateModified As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDelete As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDownloadCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDownloadCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblExtension control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExtension As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIcon As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIconUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIconUrl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIsAlternate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIsAlternate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIsFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIsFile As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIsFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIsFolder As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNameNoExtension control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNameNoExtension As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSecure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecure As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSize As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dshTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTerms As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTermsConditions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTermsConditions As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plEnableTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableTerms As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableTerms As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEnableTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnableTerms As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plTermsTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTermsTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerms As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
